apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
  namespace: default
spec:
  selector:
    app: my-nginx
  ports:
    - nodePort: 31001
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
