name: CICD Workflow - github - docker - argocd

on:
  push:
    branches:
      - main

jobs:
  cicd-build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Push Docker Image to DockerHub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        IMAGE_TAG=${{ github.sha }}
        DOCKER_IMAGE=docker.io/ghadafs/nginx:${IMAGE_TAG}
        docker build -t $DOCKER_IMAGE .
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.io
        docker push $DOCKER_IMAGE
  
    - name: Update the Deployment YAML file
      run: |
        sed -i "s#docker.io.*#docker.io/ghadafs/nginx:${{ github.sha }}#g" Deployment.yaml

    - name: Commit and Push Updated Deployment YAML
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Deployment.yaml
        git commit -m "Updated with new image tag! :)"
        git push
